routes/user.php
<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\DashboardUserController;
use App\Http\Controllers\KonsultasiController;
use App\Http\Controllers\CeritaController;
use App\Http\Controllers\CurhatController;
use App\Http\Controllers\MotivasiController;
use App\Http\Controllers\MusicController;
use App\Http\Controllers\TourController;
use Illuminate\Support\Facades\Route;

Route::get('/', [BerandaController::class, 'index'])->name("beranda");

Route::get('/signin', [AuthController::class, 'index'])->name("signin");
Route::post('/signin', [AuthController::class, 'auth'])->name("auth");

Route::get('/signup', [AuthController::class, 'signup'])->name("signup");
Route::post('/signup', [AuthController::class, 'register'])->name("register");

Route::prefix('user')->name('user.')->middleware("auth")->group(function () {

  Route::get('/', [DashboardUserController::class, 'index'])->name("index");
  Route::get('/rekomendasi', [DashboardUserController::class, 'rekomendasi'])->name("rekomendasi");
  Route::get('/about', [DashboardUserController::class, 'about'])->name("about");
  Route::get('/informasi', [DashboardUserController::class, 'informasi'])->name("informasi");

  Route::get('/konsultasi', [KonsultasiController::class, 'index'])->name("konsultasi");
  Route::get('/konsultasi/create', [KonsultasiController::class, 'create'])->name("konsultasi.create");
  Route::post('/konsultasi/store', [KonsultasiController::class, 'store'])->name("konsultasi.store");

  Route::get('/cerita/create', [CeritaController::class, 'create'])->name("cerita.create");
  Route::post('/cerita', [CeritaController::class, 'store'])->name("cerita.store");

  Route::get('/curhat', [CurhatController::class, 'index'])->name("curhat.index");
  Route::post('/curhat', [CurhatController::class, 'store'])->name("curhat.store");

});

routes/web.php
<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BerandaController;

use App\Http\Controllers\MoodController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\TodolistController;
use App\Http\Controllers\UserController;

use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\DashboardUserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [BerandaController::class, 'index'])->name("beranda")->middleware("auth");
Route::get('/track-mood', [BerandaController::class, 'mood'])->name("mood")->middleware("auth");
Route::get('/article', [BerandaController::class, 'artikel'])->name("artikel")->middleware("auth");
Route::get('/article/{artikel}', [BerandaController::class, 'artikel_detail'])->name("artikel-detail")->middleware("auth");
Route::post('/profile', [BerandaController::class, 'update_profile'])->name("update_profile");

Route::get('/mood/{type}', [MoodController::class, 'store'])->name("mood-add")->middleware("auth");

Route::resource('/todolist', TodolistController::class)->middleware("auth");


Route::get('/signin', [AuthController::class, 'login'])->name("signin");
Route::post('/sigin', [AuthController::class, 'auth'])->name("auth");
Route::get('/signup', [AuthController::class, 'register'])->name("signup");
Route::post('/signup', [AuthController::class, 'store'])->name("register");
Route::get('/logout', [AuthController::class, 'logout'])->name("logout");

Route::prefix('dashboard')->name('dashboard.')->group(function () {
  
  Route::get('/', function() {
    return redirect("dashboard/artikel");
  })->name("index");

  Route::get('/signin', [AdminAuthController::class, 'index'])->name("signin");
  Route::post('/signin', [AdminAuthController::class, 'auth'])->name("auth");
  Route::get('/logout', [AdminAuthController::class, 'logout'])->name("logout");

  Route::resource('/mood', MoodController::class);
  Route::resource('/artikel', ArtikelController::class);

  Route::get('/user', [UserController::class, 'index'])->name("user.index");

  Route::get('/logout', [AdminAuthController::class, 'logout'])->name("logout");
});

resources/views/dashboard/index.blade.php
@extends('dashboard.layout')

@section('content')

<div class="content-wrapper">
  
  <div class="row">
    
    <div class="col-12 d-flex grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <div class="d-flex flex-wrap justify-content-between">
            <h4 class="card-title mb-3">Data</h4>
          </div>
          <div class="row">
            <div class="col-12">
              <div class="d-md-flex mb-4">
                <div class="mr-md-5 mb-4">
                  <h5 class="mb-1"><i class="typcn typcn-globe-outline mr-1"></i>Artikel</h5>
                  <h2 class="text-primary mb-1 font-weight-bold">{{ $artikel }}</h2>
                </div>
                <div class="mr-md-5 mb-4">
                  <h5 class="mb-1"><i class="typcn typcn-archive mr-1"></i>Mood</h5>
                  <h2 class="text-secondary mb-1 font-weight-bold">{{ 0 }}</h2>
                </div>
                <div class="mr-md-5 mb-4">
                  <h5 class="mb-1"><i class="typcn typcn-tags mr-1"></i>User</h5>
                  <h2 class="text-warning mb-1 font-weight-bold">{{ 0 }}</h2>
                </div>
              </div>
              <canvas id="salesanalyticChart"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>
  
  </div>
 
</div>

@endsection

resources/views/dashboard/layout.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard Admin</title>
    <!-- base:css -->
    <link rel="stylesheet" href="{{ asset("assets/dashboard/vendors/typicons.font/font/typicons.css") }}">
    <link rel="stylesheet" href="{{ asset("assets/dashboard/vendors/css/vendor.bundle.base.css") }}">
    <!-- endinject --> 
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{ asset("assets/dashboard/css/vertical-layout-light/style.css") }}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{{ asset("assets/dashboard/images/favicon.png") }}" />
  </head>
  <body>
    <div class="row" id="proBanner">
      <div class="col-12">
        <span class="d-flex align-items-center purchase-popup">
          <p>Get tons of UI components, Plugins, multiple layouts, 20+ sample pages, and more!</p>
          <a href="https://www.bootstrapdash.com/product/celestial-admin-template/?utm_source=organic&utm_medium=banner&utm_campaign=free-preview" target="_blank" class="btn download-button purchase-button ml-auto">Upgrade To Pro</a>
          <i class="typcn typcn-delete-outline" id="bannerClose"></i>
        </span>
      </div>
    </div>
    <div class="container-scroller">

      <!-- partial:partials/_navbar.html -->
      @include('dashboard.partials.navbar')
      <!-- partial -->

      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_settings-panel.html -->
        <div class="theme-setting-wrapper">
          <div id="settings-trigger"><i class="typcn typcn-cog-outline"></i></div>
          <div id="theme-settings" class="settings-panel">
            <i class="settings-close typcn typcn-delete-outline"></i>
            <p class="settings-heading">SIDEBAR SKINS</p>
            <div class="sidebar-bg-options" id="sidebar-light-theme">
              <div class="img-ss rounded-circle bg-light border mr-3"></div>
              Light
            </div>
            <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
              <div class="img-ss rounded-circle bg-dark border mr-3"></div>
              Dark
            </div>
            <p class="settings-heading mt-2">HEADER SKINS</p>
            <div class="color-tiles mx-0 px-4">
              <div class="tiles success"></div>
              <div class="tiles warning"></div>
              <div class="tiles danger"></div>
              <div class="tiles primary"></div>
              <div class="tiles info"></div>
              <div class="tiles dark"></div>
              <div class="tiles default border"></div>
            </div>
          </div>
        </div>
        <!-- partial -->

        <!-- partial:partials/_sidebar.html -->
        @include('dashboard.partials.sidebar')
        <!-- partial -->

        <div class="main-panel">
          

          @yield('content')
          <!-- content-wrapper ends -->

          <!-- partial:partials/_footer.html -->
          @include('dashboard.partials.footer')
          <!-- partial -->

        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- base:js -->
    <script src="{{ asset("assets/dashboard/vendors/js/vendor.bundle.base.js") }}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src={{ asset("assets/dashboard/js/off-canvas.js") }}"></script>
    <script src={{ asset("assets/dashboard/js/hoverable-collapse.js") }}"></script>
    <script src={{ asset("assets/dashboard/js/template.js") }}"></script>
    <script src={{ asset("assets/dashboard/js/settings.js") }}"></script>
    <script src={{ asset("assets/dashboard/js/todolist.js") }}"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <script src="{{ asset("assets/dashboard/vendors/progressbar.js/progressbar.min.js") }}"></script>
    <script src="{{ asset("assets/dashboard/vendors/chart.js/Chart.min.js") }}"></script>
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <script src={{ asset("assets/dashboard/js/dashboard.js") }}"></script>
    <!-- End custom js for this page-->
  </body>
</html>

resources/views/dashboard/signin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Signin Admin</title>
  <link rel="stylesheet" href="{{ asset("assets/dashboard/vendors/typicons.font/font/typicons.css") }}">
  <link rel="stylesheet" href="{{ asset("assets/dashboard/vendors/css/vendor.bundle.base.css") }}">
  <link rel="stylesheet" href="{{ asset("assets/dashboard/css/vertical-layout-light/style.css") }}">
  <link rel="shortcut icon" href="{{ asset("assets/dashboard/images/favicon.png") }}" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo">
                <img src="{{ asset("assets/dashboard/images/logo.svg") }}" alt="logo">
              </div>
              <h4>Hello! let's get started</h4>
              <h6 class="font-weight-light">Sign in to continue.</h6>

              @if (session()->has("error"))
                  <div class="alert alert-danger">
                    {{ session("error") }}
                  </div>
              @endif

              <form class="pt-3" method="POST" action="{{ route("dashboard.auth") }}">
                @csrf
                <div class="form-group">
                  <input type="email" class="form-control form-control-lg" id="exampleInputEmail1" placeholder="Username" name="email">
                </div>
                <div class="form-group">
                  <input type="password" class="form-control form-control-lg" id="exampleInputPassword1" placeholder="Password" name="password">
                </div>
                <div class="mt-3">
                  <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" >SIGN IN</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- base:js -->
  <script src="../../vendors/js/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="../../js/off-canvas.js"></script>
  <script src="../../js/hoverable-collapse.js"></script>
  <script src="../../js/template.js"></script>
  <script src="../../js/settings.js"></script>
  <script src="../../js/todolist.js"></script>
  <!-- endinject -->
</body>

</html>