routes/user.php
<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\DashboardUserController;
use App\Http\Controllers\KonsultasiController;
use App\Http\Controllers\CeritaController;
use App\Http\Controllers\CurhatController;
use App\Http\Controllers\MotivasiController;
use App\Http\Controllers\MusicController;
use App\Http\Controllers\TourController;
use Illuminate\Support\Facades\Route;

Route::get('/', [BerandaController::class, 'index'])->name("beranda");

Route::get('/signin', [AuthController::class, 'index'])->name("signin");
Route::post('/signin', [AuthController::class, 'auth'])->name("auth");

Route::get('/signup', [AuthController::class, 'signup'])->name("signup");
Route::post('/signup', [AuthController::class, 'register'])->name("register");

Route::prefix('user')->name('user.')->middleware("auth")->group(function () {

  Route::get('/', [DashboardUserController::class, 'index'])->name("index");
  Route::get('/rekomendasi', [DashboardUserController::class, 'rekomendasi'])->name("rekomendasi");
  Route::get('/about', [DashboardUserController::class, 'about'])->name("about");
  Route::get('/informasi', [DashboardUserController::class, 'informasi'])->name("informasi");

  Route::get('/konsultasi', [KonsultasiController::class, 'index'])->name("konsultasi");
  Route::get('/konsultasi/create', [KonsultasiController::class, 'create'])->name("konsultasi.create");
  Route::post('/konsultasi/store', [KonsultasiController::class, 'store'])->name("konsultasi.store");

  Route::get('/cerita/create', [CeritaController::class, 'create'])->name("cerita.create");
  Route::post('/cerita', [CeritaController::class, 'store'])->name("cerita.store");

  Route::get('/curhat', [CurhatController::class, 'index'])->name("curhat.index");
  Route::post('/curhat', [CurhatController::class, 'store'])->name("curhat.store");

});

routes/web.php
<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BerandaController;

use App\Http\Controllers\MoodController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\TodolistController;
use App\Http\Controllers\UserController;

use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\DashboardUserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [BerandaController::class, 'index'])->name("beranda")->middleware("auth");
Route::get('/track-mood', [BerandaController::class, 'mood'])->name("mood")->middleware("auth");
Route::get('/article', [BerandaController::class, 'artikel'])->name("artikel")->middleware("auth");
Route::get('/article/{artikel}', [BerandaController::class, 'artikel_detail'])->name("artikel-detail")->middleware("auth");
Route::post('/profile', [BerandaController::class, 'update_profile'])->name("update_profile");

Route::get('/mood/{type}', [MoodController::class, 'store'])->name("mood-add")->middleware("auth");

Route::resource('/todolist', TodolistController::class)->middleware("auth");


Route::get('/signin', [AuthController::class, 'login'])->name("signin");
Route::post('/sigin', [AuthController::class, 'auth'])->name("auth");
Route::get('/signup', [AuthController::class, 'register'])->name("signup");
Route::post('/signup', [AuthController::class, 'store'])->name("register");
Route::get('/logout', [AuthController::class, 'logout'])->name("logout");

Route::prefix('dashboard')->name('dashboard.')->group(function () {
  
  Route::get('/', function() {
    return redirect("dashboard/artikel");
  })->name("index");

  Route::get('/signin', [AdminAuthController::class, 'index'])->name("signin");
  Route::post('/signin', [AdminAuthController::class, 'auth'])->name("auth");
  Route::get('/logout', [AdminAuthController::class, 'logout'])->name("logout");

  Route::resource('/mood', MoodController::class);
  Route::resource('/artikel', ArtikelController::class);

  Route::get('/user', [UserController::class, 'index'])->name("user.index");

  Route::get('/logout', [AdminAuthController::class, 'logout'])->name("logout");
});

resources/views/dashboard/partials/footer.blade.php
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-center text-sm-left d-block d-sm-inline-block">Copyright © <a href="https://www.bootstrapdash.com/" target="_blank">bootstrapdash.com</a> 2020</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Free <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap dashboard </a>templates from Bootstrapdash.com</span>
  </div>
</footer>

resources/views/dashboard/partials/navbar.blade.php
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo" href="index.html"><img src="{{ asset("assets/dashboard/images/logo.svg") }}" alt="logo"/></a>
    <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{{ asset("assets/dashboard/images/logo-mini.svg") }}" alt="logo"/></a>
    <button class="navbar-toggler navbar-toggler align-self-center d-none d-lg-flex" type="button" data-toggle="minimize">
      <span class="typcn typcn-th-menu"></span>
    </button>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle  pl-0 pr-0" href="#" data-toggle="dropdown" id="profileDropdown">
          <i class="typcn typcn-user-outline mr-0"></i>
          <span class="nav-profile-name">Evan Morales</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
          <a class="dropdown-item">
          <i class="typcn typcn-cog text-primary"></i>
          Settings
          </a>
          <a class="dropdown-item">
          <i class="typcn typcn-power text-primary"></i>
          Logout
          </a>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="typcn typcn-th-menu"></span>
    </button>
  </div>
</nav>

resources/views/dashboard/partials/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item">
      <div class="d-flex sidebar-profile">
        <div class="sidebar-profile-image">
          <img src="{{ asset("assets/dashboard/images/faces/face2.jpg") }}" alt="image">
          <span class="sidebar-status-indicator"></span>
        </div>
        <div class="sidebar-profile-name">
          <p class="sidebar-name">
            Administrator
          </p>
          <p class="sidebar-designation">
            Welcome
          </p>
        </div>
      </div>
     
      <p class="sidebar-menu-title">Dash menu</p>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ route("dashboard.index") }}">
        <i class="typcn typcn-device-desktop menu-icon"></i>
        <span class="menu-title">Dashboard</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{ route("dashboard.artikel.index") }}">
        <i class="typcn typcn-document-text menu-icon"></i>
        <span class="menu-title">Artikel</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{ route("dashboard.mood.index") }}">
        <i class="typcn typcn-compass menu-icon"></i>
        <span class="menu-title">History Mood User</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{ route("dashboard.user.index") }}">
        <i class="typcn typcn-user-add-outline menu-icon"></i>
        <span class="menu-title">Account User</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{ route("dashboard.logout") }}">
        <i class="typcn typcn-user-add-outline menu-icon"></i>
        <span class="menu-title">Logout</span>
      </a>
    </li>

  </ul>
</nav>