routes/user.php
<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\DashboardUserController;
use App\Http\Controllers\KonsultasiController;
use App\Http\Controllers\CeritaController;
use App\Http\Controllers\CurhatController;
use App\Http\Controllers\MotivasiController;
use App\Http\Controllers\MusicController;
use App\Http\Controllers\TourController;
use Illuminate\Support\Facades\Route;

Route::get('/', [BerandaController::class, 'index'])->name("beranda");

Route::get('/signin', [AuthController::class, 'index'])->name("signin");
Route::post('/signin', [AuthController::class, 'auth'])->name("auth");

Route::get('/signup', [AuthController::class, 'signup'])->name("signup");
Route::post('/signup', [AuthController::class, 'register'])->name("register");

Route::prefix('user')->name('user.')->middleware("auth")->group(function () {

  Route::get('/', [DashboardUserController::class, 'index'])->name("index");
  Route::get('/rekomendasi', [DashboardUserController::class, 'rekomendasi'])->name("rekomendasi");
  Route::get('/about', [DashboardUserController::class, 'about'])->name("about");
  Route::get('/informasi', [DashboardUserController::class, 'informasi'])->name("informasi");

  Route::get('/konsultasi', [KonsultasiController::class, 'index'])->name("konsultasi");
  Route::get('/konsultasi/create', [KonsultasiController::class, 'create'])->name("konsultasi.create");
  Route::post('/konsultasi/store', [KonsultasiController::class, 'store'])->name("konsultasi.store");

  Route::get('/cerita/create', [CeritaController::class, 'create'])->name("cerita.create");
  Route::post('/cerita', [CeritaController::class, 'store'])->name("cerita.store");

  Route::get('/curhat', [CurhatController::class, 'index'])->name("curhat.index");
  Route::post('/curhat', [CurhatController::class, 'store'])->name("curhat.store");

});

routes/web.php
<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BerandaController;

use App\Http\Controllers\MoodController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\TodolistController;
use App\Http\Controllers\UserController;

use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\DashboardUserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [BerandaController::class, 'index'])->name("beranda")->middleware("auth");
Route::get('/track-mood', [BerandaController::class, 'mood'])->name("mood")->middleware("auth");
Route::get('/article', [BerandaController::class, 'artikel'])->name("artikel")->middleware("auth");
Route::get('/article/{artikel}', [BerandaController::class, 'artikel_detail'])->name("artikel-detail")->middleware("auth");
Route::post('/profile', [BerandaController::class, 'update_profile'])->name("update_profile");

Route::get('/mood/{type}', [MoodController::class, 'store'])->name("mood-add")->middleware("auth");

Route::resource('/todolist', TodolistController::class)->middleware("auth");


Route::get('/signin', [AuthController::class, 'login'])->name("signin");
Route::post('/sigin', [AuthController::class, 'auth'])->name("auth");
Route::get('/signup', [AuthController::class, 'register'])->name("signup");
Route::post('/signup', [AuthController::class, 'store'])->name("register");
Route::get('/logout', [AuthController::class, 'logout'])->name("logout");

Route::prefix('dashboard')->name('dashboard.')->group(function () {
  
  Route::get('/', function() {
    return redirect("dashboard/artikel");
  })->name("index");

  Route::get('/signin', [AdminAuthController::class, 'index'])->name("signin");
  Route::post('/signin', [AdminAuthController::class, 'auth'])->name("auth");
  Route::get('/logout', [AdminAuthController::class, 'logout'])->name("logout");

  Route::resource('/mood', MoodController::class);
  Route::resource('/artikel', ArtikelController::class);

  Route::get('/user', [UserController::class, 'index'])->name("user.index");

  Route::get('/logout', [AdminAuthController::class, 'logout'])->name("logout");
});

app/Models/Artikel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Artikel extends Model
{
    use HasFactory;

    public $table = "artikel";
    public $guarded = ["id"];
}

app/Http/Controllers/ArtikelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Artikel;

class ArtikelController extends Controller
{
    //
    public function index()
    {
        return view("dashboard.artikel.index", [
            "hal" => "Artikel",
            "data" => Artikel::get(),
        ]);
    }

    public function create($value='')
    {
        return view("dashboard.artikel.create", [
            "hal" => "Artikel",
        ]);
    }

    public function store(Request $request)
    {
        $request->validate([
            "judul" => "required",
            "desk" => "required",
            "image" => "required",
        ]);

        $artikel = new Artikel;
        $artikel->judul = $request->judul;
        $artikel->desk = $request->desk;

        $filename  = "";

        if ($request->file("image")) {
            $file = $request->file("image");
            $filename = time() . "."  . $file->getClientOriginalExtension();
            $file->move("assets/img/artikel", $filename);
        }

        $artikel->img = $filename;
        $artikel->save();

       return redirect()->route("dashboard.artikel.index")->with("success", "Artikel Berhasil Ditambah!");
    }


    public function edit(Request $request, Artikel $artikel)
    {
        return view("dashboard.artikel.edit", [
            "hal" => "Artikel",
            "data" => $artikel,
        ]);
    }

    public function update(Request $request, Artikel $artikel)
    {
         $request->validate([
            "judul" => "required",
            "desk" => "required",
        ]);

        $artikel->judul = $request->judul;
        $artikel->desk = $request->desk;

        if ($request->file("image")) {
            $file = $request->file("image");
            $filename = time() . "."  . $file->getClientOriginalExtension();
            $file->move("assets/img/artikel", $filename);
            $artikel->img = $filename;
        }

        $artikel->save();

       return redirect()->route("dashboard.artikel.index")->with("success", "Artikel Berhasil Update!");
    }

    public function destroy(Artikel $artikel)
    {
        $artikel->delete();
        return redirect()->route("dashboard.artikel.index")->with("success", "Artikel Berhasil Dihapus!");
    }


}

resources/views/dashboard/artikel/create.blade.php
@extends('dashboard.layout')

@section('content')

<div class="content-wrapper">
  <div class="row">
    
    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Artikel Baru</h4>

          <form class="forms-sample" method="POST" action="{{ route("dashboard.artikel.store") }}" enctype="multipart/form-data">
            @csrf

            <div class="form-group">
              <label for="judul">Judul</label>
              <input type="text" class="form-control @error("judul") is-invalid @enderror" id="judul" placeholder="Judul" name="judul" value="{{ old("judul") }}">
            </div>

            <div class="form-group">
              <label for="desk">Deskripsi</label>
              <textarea name="desk" id="desk" cols="30" rows="10" class="form-control @error("desk") is-invalid @enderror">{{ old("desk") }}</textarea>
            </div>

            <div class="form-group">
              <label for="image">Gambar</label>
              <input type="file" class="form-control @error("image") is-invalid @enderror" id="image" placeholder="image" name="image">
            </div>


            <button type="submit" class="btn btn-sm btn-primary mr-2">Submit</button>
            <a href="{{ route("dashboard.artikel.index") }}" class="btn btn-sm btn-light">Kembali</a>
          </form>

        </div>
      </div>
    </div>
   
  </div>
</div>

@endsection

resources/views/dashboard/artikel/edit.blade.php
@extends('dashboard.layout')

@section('content')

<div class="content-wrapper">
  <div class="row">
    
    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Edit Artikel</h4>

          <form class="forms-sample" method="POST" action="{{ route("dashboard.artikel.update", $data->id) }}" enctype="multipart/form-data">
            @csrf
            @method("put")

           <div class="form-group">
              <label for="judul">Judul</label>
              <input type="text" class="form-control @error("judul") is-invalid @enderror" id="judul" placeholder="Judul" name="judul" value="{{ old("judul", $data->judul) }}">
            </div>

            <div class="form-group">
              <label for="desk">Deskripsi</label>
              <textarea name="desk" id="desk" cols="30" rows="10" class="form-control @error("desk") is-invalid @enderror">{{ old("desk", $data->desk) }}</textarea>
            </div>

            <div class="form-group">
              <label for="image">Image Baru</label>
              <input type="file" class="form-control" id="image" placeholder="image" name="image">
            </div>


            <button type="submit" class="btn btn-sm btn-primary mr-2">Submit</button>
            <a href="{{ route("dashboard.artikel.index") }}" class="btn btn-sm btn-light">Kembali</a>
          </form>

        </div>
      </div>
    </div>
   
  </div>
</div>

@endsection

resources/views/dashboard/artikel/index.blade.php
@extends('dashboard.layout')

@section('content')

<div class="content-wrapper">
  <div class="row">
    
    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Artikel</h4>

          <a href="{{ route("dashboard.artikel.create") }}" class="btn btn-primary btn-sm d-inline-block mb-3">Tambah Artikel</a>

          @if (session()->has("success"))
              <div class="alert alert-success">
                {{ session("success") }}
              </div>
          @endif
          
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>
                    #
                  </th>
                  <th>
                    Gambar
                  </th>
                  <th>
                    Judul
                  </th>
                  <th>
                    Deskripsi
                  </th>
                  <th>
                    Aksi
                  </th>
                </tr>
              </thead>
              <tbody>

                @if ($data)
                    @foreach ($data as $item)
                        <tr>
                          <td>{{ $loop->iteration }}</td>
                          <td>
                            <img src="{{ asset("assets/img/artikel/" . $item->img) }}" style="width: 100px; border-radius: 0px; height: inherit" alt="">
                          </td>
                          <td>
                            {{ $item->judul }}
                          </td>
                          <td>
                            {{ viewtext( $item->desk, 100 ) }}
                          </td>
                          <td>
                            <a href="{{ route("dashboard.artikel.edit", $item->id) }}" class="btn btn-sm btn-light">Edit</a>

                            <form action="{{ route("dashboard.artikel.destroy", $item->id) }}" class="d-inline" method="POST">
                              @csrf
                              @method("delete")
                              <button class="btn btn-sm btn-danger">Hapus</button>
                            </form>
                          </td>
                        </tr>
                    @endforeach
                @endif
                
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
   
  </div>
</div>

@endsection